// 각자 입맛에 맞게 변경해서 사용하기.
###
@baseUrl = http://localhost:4000/api
@listingId = listing-user1-11
@token = {{offerId}}
@offerId = {accesstoken}
# 교환 승인
#
PATCH {{baseUrl}}/marketplace/{{offerId}}/accept
Authorization: Bearer {{token}}
Content-Type: application/json

### 교환 거절
PATCH http://localhost:4000/api/marketplace/{{offerId}}/reject
Authorization: Bearer {{token}}
Content-Type: application/json
