@baseUrl = http://localhost:4000/api
@listingId = listing-user1-11
# @token = {{ACCESS_TOKEN}} 

POST {{baseUrl}}/marketplace/{{listingId}}/purchase
# Authorization: Bearer {{token}}
Content-Type: application/json

{

  "quantity": 1,
    "buyerId": "user2"
}
