const User = [
  {
    id: "user-1",
    providerId: "google-uid-1001",
    providerType: "GOOGLE",
    email: "yudi@gmail.com",
    name: "유디",
    password: null,
    refreshtoken: "refresh-token-google-1001",
    isDeleted: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "user-2",
    providerId: "google-uid-1002",
    providerType: "GOOGLE",
    email: "yeonwoo@gmail.com",
    name: "연우",
    password: null,
    refreshtoken: "refresh-token-google-1002",
    isDeleted: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "user-3",
    providerId: null,
    providerType: "EMAIL",
    email: "1234@example.com",
    name: "다혜",
    password: "12345678",
    refreshtoken: "refresh-token-email-1",
    isDeleted: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "user-4",
    providerId: null,
    providerType: "EMAIL",
    email: "5678@example.com",
    name: "희성",
    password: "11111111",
    refreshtoken: "refresh-token-email-2",
    isDeleted: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "user-5",
    providerId: null,
    providerType: "EMAIL",
    email: "example@example.com",
    name: "수현",
    password: "12341234",
    refreshtoken: "refresh-token-email-3",
    isDeleted: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export default User;
